
name: test-demo-workflow
run-name: ${{github.actor}} testing our github action
on: 
  push: 
    branches: 
      - main

jobs: 
  first-job:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: pwd run
        shell: bash
        run: pwd

      - name: checkout
        uses: actions/checkout@v4        

      - name: pwd run
        shell: bash
        run: ls
      
      # - name: print workspace
      #   shell: bash
      #   run: go run main.go

      env: 
        keys: ${{secrets.MYJWT}}

      - name: environment secret
        shell: bash
        run: echo keys

      # - name:  install
      #   shell: bash
      #   run: sudo apt install tree

      # - name:  tree
      #   shell: bash
      #   run: treeing