name: test-demo-workflow
run-name: ${{ github.actor }} testing our GitHub action
on: 
  push: 
    branches: 
      - main

jobs: 
  first-job:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout
        uses: actions/checkout@v4        

      - name: Print Working Directory
        shell: bash
        run: pwd

      - name: List Files
        shell: bash
        run: ls

      - name: Access Environment Secret
        shell: bash
        env: 
          keys: ${{ secrets.MYJWT }}
        run: echo $keys
